# distributed training
nodes: 1
gpus: 1 # I recommend always assigning 1 GPU to 1 node
nr: 0 # machine nr. in node (0 -- nodes - 1)
dataparallel: 0 # Use DataParallel instead of DistributedDataParallel
workers: 8
dataset_dir: "./datasets"

# train options
seed: 42 # sacred handles automatic seeding when passed in the config
batch_size: 128
image_size: 272
start_epoch: 0
epochs: 100
dataset: "ADP-Release1" # STL10, CIFAR10, ADP-Release1
pretrain: True

# model options
resnet: "resnet18"
projection_dim: 64 # "[...] to project the representation to a 128-dimensional latent space"

# loss options
optimizer: "Adam" # "SGD", "Adam" or LARS (experimental)
# scheduler: "cosLR" # "cosLR or stepLR"
weight_decay: 1.0e-6 # 1.0e-6 "optimized using LARS [...] and weight decay of 10−6"
temperature: 0.5 # see appendix B.7.: Optimal temperature under different batch sizes
# momentum: 0.9

# reload options
model_path: "save_adp_adam" # set to the directory containing `checkpoint_##.tar`
epoch_num: 0 # set to checkpoint number
reload: False

# logistic regression options
logistic_batch_size: 256
logistic_epochs: 500
