#!/bin/bash
sbatch runBCSS_transformed-AdamP-lr-0.001-OSDataset_transformed-norm-ImageNet-None.sh
sleep 2
sbatch runBCSS_transformed-AdamP-lr-0.001-CRC_transformed-norm-ImageNet-None.sh
sleep 2
sbatch runBCSS_transformed-AdamP-lr-0.001-AJ-Lymph_transformed-norm-ImageNet-None.sh
sleep 2
sbatch runBCSS_transformed-AdamP-lr-0.001-BACH_transformed-norm-ImageNet-None.sh
sleep 2
sbatch runBCSS_transformed-AdamP-lr-0.001-GlaS_transformed-norm-ImageNet-None.sh
sleep 2
sbatch runBCSS_transformed-AdamP-lr-0.001-MHIST_transformed-norm-ImageNet-None.sh
sleep 2
sbatch runBCSS_transformed-AdamP-lr-0.001-PCam_transformed-norm-ImageNet-None.sh
sleep 2
sbatch runOSDataset_transformed-AdamP-lr-0.0001-BCSS_transformed-norm-ImageNet-None.sh
sleep 2
sbatch runOSDataset_transformed-AdamP-lr-0.0001-CRC_transformed-norm-ImageNet-None.sh
sleep 2
sbatch runOSDataset_transformed-AdamP-lr-0.0001-AJ-Lymph_transformed-norm-ImageNet-None.sh
sleep 2
sbatch runOSDataset_transformed-AdamP-lr-0.0001-BACH_transformed-norm-ImageNet-None.sh
sleep 2
sbatch runOSDataset_transformed-AdamP-lr-0.0001-GlaS_transformed-norm-ImageNet-None.sh
sleep 2
sbatch runOSDataset_transformed-AdamP-lr-0.0001-MHIST_transformed-norm-ImageNet-None.sh
sleep 2
sbatch runOSDataset_transformed-AdamP-lr-0.0001-PCam_transformed-norm-ImageNet-None.sh
sleep 2
sbatch runCRC_transformed-AdamP-lr-0.0005-BCSS_transformed-norm-ImageNet-None.sh
sleep 2
sbatch runCRC_transformed-AdamP-lr-0.0005-OSDataset_transformed-norm-ImageNet-None.sh
sleep 2
sbatch runCRC_transformed-AdamP-lr-0.0005-AJ-Lymph_transformed-norm-ImageNet-None.sh
sleep 2
sbatch runCRC_transformed-AdamP-lr-0.0005-BACH_transformed-norm-ImageNet-None.sh
sleep 2
sbatch runCRC_transformed-AdamP-lr-0.0005-GlaS_transformed-norm-ImageNet-None.sh
sleep 2
sbatch runCRC_transformed-AdamP-lr-0.0005-MHIST_transformed-norm-ImageNet-None.sh
sleep 2
sbatch runCRC_transformed-AdamP-lr-0.0005-PCam_transformed-norm-ImageNet-None.sh
sleep 2
